title: Marc-André Simoneau
email: marc-andre.simoneau@hotmail.com
description: "A quiet corner of the web for learning, building, and writing at a human pace."
baseurl: ""
url: "https://marcandresimoneau.com"

social_links:
  github: https://github.com/Insomniac21
  linkedin: https://www.linkedin.com/in/marc-andr%C3%A9-simoneau-1b8669111/

header_pages:
  - index.md

theme: just-the-docs

just_the_docs:
  search_enabled: true

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  postman:
    output: true
    permalink: "/:collection/:path/"
  stardewvalley:
    output: true
    permalink: "/:collection/:path/"

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    postman:
      # Give the collection a name
      name: Postman
    stardewvalley:
      name: Stardew Valley

exclude:
  - templates/
  - draft-template.md
  - notes/
